"""add is_deleted field to companies

Revision ID: 0c7818feea81
Revises: b1b6f4a5f415
Create Date: 2026-05-21 14:21:10.306995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7818feea81'
down_revision: Union[str, Sequence[str], None] = 'b1b6f4a5f415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'is_deleted')
    # ### end Alembic commands ###
