"""updated cancell function

Revision ID: 1d30399b58fc
Revises: 5bfc3b79ef8e
Create Date: 2026-04-30 11:06:48.972204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d30399b58fc'
down_revision: Union[str, Sequence[str], None] = '5bfc3b79ef8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('containers', sa.Column('cancel_reason', sa.String(), nullable=True))
    op.drop_column('containers', 'cancellation_reason')
    op.drop_column('containers', 'cancellation_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('cancellation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('containers', sa.Column('cancellation_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('containers', 'cancel_reason')
    op.drop_column('containers', 'cancelled_at')
    # ### end Alembic commands ###
