"""Add precarriage, oncarriage

Revision ID: 1fd983bbffee
Revises: 45b9ebb8a7bf
Create Date: 2026-04-27 14:54:09.343566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd983bbffee'
down_revision: Union[str, Sequence[str], None] = '45b9ebb8a7bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargo_orders', sa.Column('pre_carriage_required', sa.Boolean(), nullable=True))
    op.add_column('cargo_orders', sa.Column('pre_carriage_address', sa.String(), nullable=True))
    op.add_column('cargo_orders', sa.Column('pre_carriage_contact', sa.String(), nullable=True))
    op.add_column('cargo_orders', sa.Column('pre_carriage_date', sa.DateTime(), nullable=True))
    op.add_column('cargo_orders', sa.Column('pre_carriage_comment', sa.String(), nullable=True))
    op.add_column('cargo_orders', sa.Column('on_carriage_required', sa.Boolean(), nullable=True))
    op.add_column('cargo_orders', sa.Column('on_carriage_address', sa.String(), nullable=True))
    op.add_column('cargo_orders', sa.Column('on_carriage_contact', sa.String(), nullable=True))
    op.add_column('cargo_orders', sa.Column('on_carriage_date', sa.DateTime(), nullable=True))
    op.add_column('cargo_orders', sa.Column('on_carriage_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cargo_orders', 'on_carriage_comment')
    op.drop_column('cargo_orders', 'on_carriage_date')
    op.drop_column('cargo_orders', 'on_carriage_contact')
    op.drop_column('cargo_orders', 'on_carriage_address')
    op.drop_column('cargo_orders', 'on_carriage_required')
    op.drop_column('cargo_orders', 'pre_carriage_comment')
    op.drop_column('cargo_orders', 'pre_carriage_date')
    op.drop_column('cargo_orders', 'pre_carriage_contact')
    op.drop_column('cargo_orders', 'pre_carriage_address')
    op.drop_column('cargo_orders', 'pre_carriage_required')
    # ### end Alembic commands ###
