"""counterparties fixes

Revision ID: 239bd09d830a
Revises: eeffd989d475
Create Date: 2026-05-29 11:25:44.859992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239bd09d830a'
down_revision: Union[str, Sequence[str], None] = 'eeffd989d475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counterparties', sa.Column('is_carrier', sa.Boolean(), nullable=True))
    op.execute("UPDATE counterparties SET is_carrier = FALSE WHERE is_carrier IS NULL")
    op.alter_column('counterparties', 'is_carrier', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('counterparties', 'is_carrier')
    # ### end Alembic commands ###
