"""Add precarriage carrier

Revision ID: 26f988ec17cb
Revises: 1fd983bbffee
Create Date: 2026-04-27 15:52:24.054690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f988ec17cb'
down_revision: Union[str, Sequence[str], None] = '1fd983bbffee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargo_orders', sa.Column('pre_carriage_carrier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cargo_orders', 'pre_carriage_carrier')
    # ### end Alembic commands ###
