"""voyages addons

Revision ID: 2c178730f96b
Revises: d92a4537b0c3
Create Date: 2026-06-08 16:07:53.707075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c178730f96b'
down_revision: Union[str, Sequence[str], None] = 'd92a4537b0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('voyages_number_key'), 'voyages', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('voyages_number_key'), 'voyages', ['number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
