"""added soc/coc to cargo order

Revision ID: 435547918e84
Revises: 1d30399b58fc
Create Date: 2026-04-30 13:35:38.997142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435547918e84'
down_revision: Union[str, Sequence[str], None] = '1d30399b58fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargo_orders', sa.Column('is_soc', sa.Boolean(), nullable=True))
    op.add_column('cargo_orders', sa.Column('return_instructions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cargo_orders', 'return_instructions')
    op.drop_column('cargo_orders', 'is_soc')
    # ### end Alembic commands ###
