"""Add is_active to Port

Revision ID: 45b9ebb8a7bf
Revises: 47bb061c0712
Create Date: 2026-04-23 14:48:33.269204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b9ebb8a7bf'
down_revision: Union[str, Sequence[str], None] = '47bb061c0712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('equipment_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'containers', 'equipments', ['equipment_id'], ['id'])
    op.add_column('ports', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ports', 'is_active')
    op.drop_constraint(None, 'containers', type_='foreignkey')
    op.drop_column('containers', 'equipment_id')
    # ### end Alembic commands ###
