"""Add ports, counterparties, equipment

Revision ID: 47bb061c0712
Revises: 1f1dacaccb49
Create Date: 2026-04-23 14:25:35.455991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47bb061c0712'
down_revision: Union[str, Sequence[str], None] = '1f1dacaccb49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    from sqlalchemy.dialects import postgresql
    transporttype_enum = postgresql.ENUM('CONTAINER', 'GENERAL_CARGO', name='transporttype')
    transporttype_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipments_name'), 'equipments', ['name'], unique=False)
    op.create_table('ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('counterparties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('inn', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparties_name'), 'counterparties', ['name'], unique=False)
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('is_soc', sa.Boolean(), nullable=True),
    sa.Column('weight_gross', sa.Float(), nullable=True),
    sa.Column('cargo_description', sa.String(), nullable=True),
    sa.Column('container_number', sa.String(), nullable=True),
    sa.Column('seal', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['cargo_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_cargo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('weight_gross', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('dimensions', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['cargo_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cargo_orders', sa.Column('status', sa.String(), nullable=True))
    op.add_column('cargo_orders', sa.Column('transport_type', sa.Enum('CONTAINER', 'GENERAL_CARGO', name='transporttype'), nullable=True))
    op.add_column('cargo_orders', sa.Column('shipper_id', sa.Integer(), nullable=True))
    op.add_column('cargo_orders', sa.Column('consignee_id', sa.Integer(), nullable=True))
    op.add_column('cargo_orders', sa.Column('notify_party_id', sa.Integer(), nullable=True))
    op.add_column('cargo_orders', sa.Column('pol_id', sa.Integer(), nullable=True))
    op.add_column('cargo_orders', sa.Column('pod_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cargo_orders', 'counterparties', ['shipper_id'], ['id'])
    op.create_foreign_key(None, 'cargo_orders', 'ports', ['pol_id'], ['id'])
    op.create_foreign_key(None, 'cargo_orders', 'ports', ['pod_id'], ['id'])
    op.create_foreign_key(None, 'cargo_orders', 'counterparties', ['notify_party_id'], ['id'])
    op.create_foreign_key(None, 'cargo_orders', 'counterparties', ['consignee_id'], ['id'])
    op.drop_column('cargo_orders', 'cargo_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargo_orders', sa.Column('cargo_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cargo_orders', type_='foreignkey')
    op.drop_constraint(None, 'cargo_orders', type_='foreignkey')
    op.drop_constraint(None, 'cargo_orders', type_='foreignkey')
    op.drop_constraint(None, 'cargo_orders', type_='foreignkey')
    op.drop_constraint(None, 'cargo_orders', type_='foreignkey')
    op.drop_column('cargo_orders', 'pod_id')
    op.drop_column('cargo_orders', 'pol_id')
    op.drop_column('cargo_orders', 'notify_party_id')
    op.drop_column('cargo_orders', 'consignee_id')
    op.drop_column('cargo_orders', 'shipper_id')
    op.drop_column('cargo_orders', 'transport_type')
    op.drop_column('cargo_orders', 'status')
    op.drop_table('general_cargo_items')
    op.drop_table('containers')
    op.drop_index(op.f('ix_counterparties_name'), table_name='counterparties')
    op.drop_table('counterparties')
    op.drop_table('ports')
    op.drop_index(op.f('ix_equipments_name'), table_name='equipments')
    op.drop_table('equipments')
    # ### end Alembic commands ###
    from sqlalchemy.dialects import postgresql
    transporttype_enum = postgresql.ENUM('CONTAINER', 'GENERAL_CARGO', name='transporttype')
    transporttype_enum.drop(op.get_bind(), checkfirst=True)
