"""make_order_fields_nullable

Revision ID: 4c55b8bf9b96
Revises: 905accfc7afd
Create Date: 2026-05-15 11:02:17.649744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c55b8bf9b96'
down_revision: Union[str, Sequence[str], None] = '905accfc7afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cargo_orders', 'loading_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('cargo_orders', 'equipment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cargo_orders', 'equipment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cargo_orders', 'loading_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
