"""counterparties new fixes

Revision ID: 4c784cd26b60
Revises: 239bd09d830a
Create Date: 2026-05-29 11:59:37.656040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c784cd26b60'
down_revision: Union[str, Sequence[str], None] = '239bd09d830a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargo_orders', sa.Column('pre_carriage_carrier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cargo_orders', 'counterparties', ['pre_carriage_carrier_id'], ['id'])
    op.drop_column('cargo_orders', 'pre_carriage_carrier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargo_orders', sa.Column('pre_carriage_carrier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cargo_orders', type_='foreignkey')
    op.drop_column('cargo_orders', 'pre_carriage_carrier_id')
    # ### end Alembic commands ###
