"""add_on_cargo_items

Revision ID: 4fd4b537a46d
Revises: d89d92ed50d3
Create Date: 2026-05-15 12:48:11.187708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd4b537a46d'
down_revision: Union[str, Sequence[str], None] = 'd89d92ed50d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('is_lcl', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('containers', 'is_lcl')
    # ### end Alembic commands ###
