"""added containers_archive table2

Revision ID: 54fd2ada8ece
Revises: 6b08dabccf00
Create Date: 2026-06-25 11:02:58.781320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54fd2ada8ece'
down_revision: Union[str, Sequence[str], None] = '6b08dabccf00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers_archive', sa.Column('source_group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('containers_archive', 'source_group')
    # ### end Alembic commands ###
