"""Add cancell function

Revision ID: 5bfc3b79ef8e
Revises: 26f988ec17cb
Create Date: 2026-04-30 09:55:58.434601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bfc3b79ef8e'
down_revision: Union[str, Sequence[str], None] = '26f988ec17cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('is_cancelled', sa.Boolean(), nullable=True))
    op.add_column('containers', sa.Column('cancelled_by_id', sa.Integer(), nullable=True))
    op.add_column('containers', sa.Column('cancellation_date', sa.DateTime(), nullable=True))
    op.add_column('containers', sa.Column('cancellation_reason', sa.String(), nullable=True))
    op.alter_column('containers', 'pieces',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'containers', 'users', ['cancelled_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'containers', type_='foreignkey')
    op.alter_column('containers', 'pieces',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('containers', 'cancellation_reason')
    op.drop_column('containers', 'cancellation_date')
    op.drop_column('containers', 'cancelled_by_id')
    op.drop_column('containers', 'is_cancelled')
    # ### end Alembic commands ###
