"""add_loading_date_and_equipment_to_cargo_orders

Revision ID: 905accfc7afd
Revises: 77ddce706af0
Create Date: 2026-05-15 10:56:52.198953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905accfc7afd'
down_revision: Union[str, Sequence[str], None] = '77ddce706af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargo_orders', sa.Column('loading_date', sa.Date(), nullable=False))
    op.add_column('cargo_orders', sa.Column('equipment_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cargo_orders', 'equipments', ['equipment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cargo_orders', type_='foreignkey')
    op.drop_column('cargo_orders', 'equipment_id')
    op.drop_column('cargo_orders', 'loading_date')
    # ### end Alembic commands ###
