"""companies issues

Revision ID: 9ce04e70b2b2
Revises: 2c178730f96b
Create Date: 2026-06-09 15:07:35.352522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce04e70b2b2'
down_revision: Union[str, Sequence[str], None] = '2c178730f96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargo_orders', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cargo_orders', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cargo_orders', type_='foreignkey')
    op.drop_column('cargo_orders', 'company_id')
    # ### end Alembic commands ###
