"""voyages and vessels added

Revision ID: 9de710b2fbc4
Revises: 6d570f596360
Create Date: 2026-06-04 14:49:10.999957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de710b2fbc4'
down_revision: Union[str, Sequence[str], None] = '6d570f596360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('voyage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'containers', 'voyages', ['voyage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'containers', type_='foreignkey')
    op.drop_column('containers', 'voyage_id')
    # ### end Alembic commands ###
