"""fixes container weight and pieces

Revision ID: b1b6f4a5f415
Revises: 4fd4b537a46d
Create Date: 2026-05-15 13:05:45.742606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b6f4a5f415'
down_revision: Union[str, Sequence[str], None] = '4fd4b537a46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('containers', 'pieces',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('containers', 'pieces',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
