"""soft delete cargo order and containers

Revision ID: bf4a4470ccb9
Revises: ccf7060730aa
Create Date: 2026-05-29 10:28:34.757244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4a4470ccb9'
down_revision: Union[str, Sequence[str], None] = 'ccf7060730aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargo_orders', sa.Column('is_valid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cargo_orders', 'is_valid')
    # ### end Alembic commands ###
