"""some fixes

Revision ID: ccf7060730aa
Revises: 90ba54df890a
Create Date: 2026-05-27 15:49:15.398181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf7060730aa'
down_revision: Union[str, Sequence[str], None] = '90ba54df890a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_inn'), table_name='companies')
    op.create_index(op.f('ix_companies_inn'), 'companies', ['inn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_inn'), table_name='companies')
    op.create_index(op.f('ix_companies_inn'), 'companies', ['inn'], unique=True)
    # ### end Alembic commands ###
