"""added soc/coc to cargo order

Revision ID: cfb87c0b7f36
Revises: 435547918e84
Create Date: 2026-04-30 13:55:04.779935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb87c0b7f36'
down_revision: Union[str, Sequence[str], None] = '435547918e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargo_orders', sa.Column('needs_return', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cargo_orders', 'needs_return')
    # ### end Alembic commands ###
