"""add_on_carriage_notes

Revision ID: d89d92ed50d3
Revises: 4c55b8bf9b96
Create Date: 2026-05-15 11:47:01.054375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd89d92ed50d3'
down_revision: Union[str, Sequence[str], None] = '4c55b8bf9b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargo_orders', sa.Column('on_carriage_notes', sa.String(), nullable=True))
    op.drop_column('cargo_orders', 'on_carriage_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargo_orders', sa.Column('on_carriage_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('cargo_orders', 'on_carriage_notes')
    # ### end Alembic commands ###
