"""voyages and vessels added

Revision ID: d92a4537b0c3
Revises: 9de710b2fbc4
Create Date: 2026-06-04 15:44:47.009474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92a4537b0c3'
down_revision: Union[str, Sequence[str], None] = '9de710b2fbc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vessels', sa.Column('voyage_count', sa.Integer(), nullable=True, comment='Количество рейсов'))
    op.add_column('vessels', sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='Дата последнего использования'))
    op.create_index(op.f('ix_vessels_last_used_at'), 'vessels', ['last_used_at'], unique=False)
    op.create_index(op.f('ix_vessels_name'), 'vessels', ['name'], unique=False)
    op.create_index(op.f('ix_vessels_voyage_count'), 'vessels', ['voyage_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vessels_voyage_count'), table_name='vessels')
    op.drop_index(op.f('ix_vessels_name'), table_name='vessels')
    op.drop_index(op.f('ix_vessels_last_used_at'), table_name='vessels')
    op.drop_column('vessels', 'last_used_at')
    op.drop_column('vessels', 'voyage_count')
    # ### end Alembic commands ###
