"""container valid added

Revision ID: e99e6a89cbb2
Revises: a8b5d9f83d5d
Create Date: 2026-05-08 11:24:57.949027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e99e6a89cbb2'
down_revision: Union[str, Sequence[str], None] = 'a8b5d9f83d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('valid_number', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('containers', 'valid_number')
    # ### end Alembic commands ###
