"""on_carrige carrier added

Revision ID: eeffd989d475
Revises: bf4a4470ccb9
Create Date: 2026-05-29 11:05:08.956172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeffd989d475'
down_revision: Union[str, Sequence[str], None] = 'bf4a4470ccb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargo_orders', sa.Column('on_carriage_carrier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cargo_orders', 'on_carriage_carrier')
    # ### end Alembic commands ###
