"""added companies and user relationship

Revision ID: fea72ae2b4ea
Revises: cfb87c0b7f36
Create Date: 2026-05-06 13:41:01.802498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea72ae2b4ea'
down_revision: Union[str, Sequence[str], None] = 'cfb87c0b7f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('inn', sa.String(), nullable=True),
    sa.Column('kpp', sa.String(), nullable=True),
    sa.Column('ogrn', sa.String(), nullable=True),
    sa.Column('address1', sa.String(), nullable=True),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('tel1', sa.String(), nullable=True),
    sa.Column('tel2', sa.String(), nullable=True),
    sa.Column('email1', sa.String(), nullable=True),
    sa.Column('email2', sa.String(), nullable=True),
    sa.Column('bik', sa.String(), nullable=True),
    sa.Column('ks', sa.String(), nullable=True),
    sa.Column('rs', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_fullname'), 'companies', ['fullname'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_inn'), 'companies', ['inn'], unique=True)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_inn'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_fullname'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
